frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/app/App.tsx, frontend/src/app/Router.tsx, frontend/src/widgets/layout/ui/Layout.tsx, frontend/src/widgets/sidebar/model/useNavigation.tsx, frontend/src/widgets/sidebar/ui/NavigationMenu.tsx
- Routing을 위한 `react-router` 패키지 추가
- Router 생성
- `dashboard`, `firmware`, `ads`, `monitoring` 에 대한 path를 생성
- 진입 지점은 `dashboard`로 설정
- `NavigationMenu`의 `NavigationItem`들의 path와 현재 경로가 같으면 `isActive` true 반환
- 로컬에서 테스트
N/A
N/A
=> Sidebar Routing 설정

frontend/src/widgets/sidebar/ui/NavigationMenu.tsx
- `NavigationMenu`의 padding을 왼쪽에만 적용
N/A
N/A
=> Sidebar Navigation 메뉴 Padding 재설정

frontend/src/app/Router.tsx, frontend/src/pages/advertisement.tsx, frontend/src/pages/dashboard.tsx, frontend/src/pages/firmware.tsx, frontend/src/pages/monitoring.tsx, frontend/src/widgets/layout/ui/Layout.tsx, frontend/src/widgets/layout/ui/TitleTile.tsx
- 각 페이지 최상단에 표시될 `TitleTile` 타일 추가
- Title & Description 표시
- 각 페이지에 `TitleTile` 컴포넌트 최상단에 추가
- Page에 `export default` 제거
- 로컬 테스팅
N/A
N/A
=> Title Tile 추가 및 적용

frontend/src/widgets/layout/ui/TitleTile.tsx
- TitleTile의 사이즈 & 두께 조정
- #12 에서 폰트를 `Pretendard`로 변경하였는데 NanumSquareRound보다 두께가 훨씬 두꺼워짐
**Before**
**After**
N/A
N/A
=> TitleTile Font Weight 변경

frontend/src/shared/ui/SearchBar.tsx
- 검색 기능을 제공하는 Widget을 추가하였습니다.
- `onSearch` 함수를 props로 받아 검색 값이 바뀐 경우 `onSearch()`를 호출합니다.
N/A
N/A
=> [Frontend] 검색 위젯 구현

frontend/src/widgets/layout/ui/MainTile.tsx
- 페이지의 상세 내용들이 들어갈 메인 타일 생성
- `검색 바`, `전체 보기` 등 버튼을 추가하기 위한 `rightElement` 생성
N/A
N/A
=> [Frontend] 메인 타일 생성

frontend/src/entities/firmware/ui/FirmwareList.tsx
- 펌웨어 리스트를 보여주는 컴포넌트를 구현하였습니다.
- 펌웨어 리스트 컴포넌트는 다음을 보여줍니다.
- 펌웨어 버전
- 업로드 시각
- 릴리즈 노트
N/A
N/A
=> [Frontend] 펌웨어 리스트 컴포넌트 구현

frontend/src/entities/firmware/api/api.ts, frontend/src/features/firmware/api/useFirmwareSearch.tsx, frontend/src/pages/firmware.tsx, frontend/src/shared/api/types.ts, frontend/src/shared/mocks/handlers.ts
- 펌웨어 API에 `search`를 추가하였습니다.
- parameter에 `query=?`를 추가하면 해당 query를 포함하는 펌웨어 버전의 리스트를 반환합니다.
- `useFirmwareSearch`라는 custom hook을 추가하여 검색 결과에 따라 펌웨어 리스트 state를 변경합니다.
- MSW에 펌웨어 검색 API 핸들러를 추가하였습니다.
https://github.com/user-attachments/assets/cec9a0bd-884b-4661-8c9d-7e9d55aeb062
N/A
N/A
=> [Frontend] 펌웨어 검색 기능 구현 & Mock API 추가

frontend/src/shared/ui/Button.tsx
- 여러 페이지에서 공통적으로 사용되는 `Button` 컴포넌트를 추가하였습니다.
- Icon 없이 Title만 있는 경우
- Icon, Title이 있는 경우
- 클릭 시 ring 추가
- Disabled 된 경우
N/A
N/A
=> [Frontend] 버튼 컴포넌트 추가

frontend/src/widgets/layout/ui/MainTile.tsx
- `Title`과 `Children` 간에 margin 4 -> 8 로 증가
N/A
N/A
=> [Frontend] 메인 타일 디자인 개선

frontend/src/entities/firmware/ui/FirmwareDetail.tsx, frontend/src/features/firmware/api/useFirmwareDetail.tsx, frontend/src/pages/FirmwareDetailPage.tsx
- 펌웨어 ID를 이용해 특정 펌웨어를 가져오는 Custom Hook `useFirmwareDetail`을 구현하였습니다.
- 펌웨어 상세 정보 페이지 컴포넌트 `FirmwareDetail`을 구현하였습니다.
- 펌웨어 상세 정보 페이지를 구현하였습니다.
N/A
N/A
=> [Frontend] 펌웨어 상세 정보 페이지 구현

frontend/src/app/Router.tsx, frontend/src/entities/firmware/ui/FirmwareList.tsx, frontend/src/pages/firmware.tsx, frontend/src/widgets/sidebar/ui/NavigationMenu.tsx
- `Router.tsx` 에 펌웨어 상세 정보 페이지를 추가하였습니다.
- 펌웨어 페이지에서 특정 펌웨어를 클릭하면 상세 정보 페이지로 라우팅되도록 하였습니다.
- 사이드바는 특정 URL로 시작하면 active 되도록 수정하였습니다. (아래 두개 모두 사이드바에 `펌웨어 관리`가 active되도록)
- 펌웨어 페이지: `/firmware/`
- 펌웨어 상세 페이지: `/firmware/:id`
https://github.com/user-attachments/assets/9f6e357a-f3d5-41e3-83a3-ec8a73a648e7
N/A
N/A
=> [Frontend] Firmware 상세 정보 페이지 Routing 구현

frontend/src/entities/firmware/model/mappers.ts, frontend/src/entities/firmware/model/types.ts, frontend/src/entities/firmware/ui/FirmwareDetail.tsx, frontend/src/shared/mocks/handlers.ts
- `Firmware` 모델에 `updatedAt`(수정 일자) 컬럼을 추가하였습니다.
N/A
N/A
=> [Frontend] Firmware에 `updatedAt` 컬럼 추가

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/entities/firmware/api/api.ts, frontend/src/entities/firmware/model/types.ts, frontend/src/features/firmware/api/useFirmwareSearch.tsx, frontend/src/pages/FirmwarePage.tsx, frontend/src/shared/api/mappers.ts, frontend/src/shared/api/types.ts, frontend/src/shared/mocks/handlers.ts
- 간단한 Pagination 구현을 위해 `react-paginate` 라이브러리를 추가하였습니다.
- Paginated된 요청의 interface를 기존 `ApiResponse`와 분리하였습니다 -> `PaginatedApiResponse` 생성
- Paginated Response는 여러 서비스에서 공통적으로 사용될 수 있으므로, `Firmware`에 있던 `Meta`를 삭제하고 `shared/api`에 추가하여 여러 서비스가 같은 `PaginationMeta` 를 사용할 수 있도록 하였습니다.
- Firmware 페이지의 펌웨어 리스트를 Pagination 적용하기 위해 `firmwareApiService`가 Paginated Meta를 반환하도록 수정하고, `useFirmwareSearch`에서 page의 상태를 저장하도록 하였습니다.
https://github.com/user-attachments/assets/7295ae58-00bc-48f4-99f5-7182ea6b92b7
N/A
N/A
=> [Frontend] Firmware 페이지네이션 구현

frontend/src/shared/ui/Button.tsx
- `Button` 컴포넌트에 `variant` 속성을 추가하여 primary & secondary 를 구분할 수 있도록 개선하였습니다.
- 취소: `secondary`, 등록: `primary`
N/A
N/A
=> [FrontEnd] Button 컴포넌트에 `variant` 속성 추가

frontend/src/shared/ui/Button.tsx
- `Button`은 목적에 따라 `button`, `submit`, `reset`이 될 수 있으므로 이에 맞게 `type` props를 추가하였습니다.
N/A
N/A
N/A
=> [FrontEnd] Button 컴포넌트에 `type` 추가

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/features/firmware/ui/FirmwareRegister.tsx, frontend/src/pages/FirmwarePage.tsx
- 펌웨어를 등록할 수 있는 모달 창을 구현하였습니다.
- 간편한 모달 창 구현을 위해 `react-modal` 라이브러리를 추가하였습니다.
- 모달 창에서 `펌웨어 버전 정보`, `릴리즈 노트`, `TFT 파일`을 받을 수 있도록 구현하였습니다.
- TODO: 백엔드 구성 이후 API 연동 예정입니다.
https://github.com/user-attachments/assets/d05aa6b9-873a-4536-a756-583c4002b922
N/A
N/A
=> [FrontEnd] Firmware 등록 모달 창 구현

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/entities/firmware/api/firmwareApi.ts, frontend/src/features/firmware/api/useFirmwareDetail.tsx, frontend/src/features/firmware/api/useFirmwareSearch.tsx, frontend/src/features/firmware/ui/FirmwareRegister.tsx, frontend/src/shared/api/zip.ts
- 펌웨어 등록 POST 요청을 보내는 `firmwareApiService.register()`를 추가하였습니다.
- 펌웨어 등록 POST 요청의 구조는 다음과 같습니다.
```
{
"version": "24.04.01",
"releaseNote": "This is Release Note",
"file": {compressed file}
}
```
+ 최소 API 요청에 대해서는 Unit Test를 추가할 예정입니다. 다음 PR (ㅎㅎ)
N/A
N/A
=> [FrontEnd] Firmware 등록 API 구현

terraform/.gitignore, terraform/.terraform.lock.hcl, terraform/providers.tf, terraform/remote-state.tf
- `aws` provider를 사용하여 AWS 리소스를 원격으로 컨트롤 할 수 있도록 하였습니다.
- `iot-cloud-ota-tf-state-bucket` S3 버켓을 이용해 Terraform State를 원격으로 관리하도록 하였습니다.
- Terraform 프로젝트에 필요한 `.gitignore`를 추가하였습니다.
- State를 저장하는 S3 버켓
N/A
N/A
=> [Terraform] Terraform 초기 설정

terraform/.terraform.lock.hcl, terraform/buckets.tf
- CloudFront Signed URL 생성 시 필요한 RSA 키 페어를 AWS Secrets Manager에 추가하였습니다.
- 키 페어 중 Public Key를 CloudFront Public Key로 등록하였습니다.
- CloudFront 키 생성 결과
- 테스트용 CloudFront Pre-signed URL 생성 람다 함수
```
import os
import boto3
import datetime
import botocore.signers
import rsa
import json
CLOUDFRONT_SECRET_NAME = os.environ.get('CLOUDFRONT_SECRET_NAME')
CLOUDFRONT_DOMAIN = os.environ.get('CLOUDFRONT_DOMAIN')
CLOUDFRONT_KEY_ID = os.environ.get('CLOUDFRONT_KEY_ID')
def get_secret():
"""Fetches the RSA private key from AWS Secrets Manager."""
client = boto3.client('secretsmanager')
response = client.get_secret_value(SecretId=CLOUDFRONT_SECRET_NAME)
secret = response['SecretString']
return secret
def rsa_signer(message):
"""Signs the message using the RSA private key."""
private_key_data = get_secret() …
```
=> [Terraform] CloudFront Signed URL 생성을 위한 RSA 키 페어 추가

frontend/src/entities/region/api/regionApi.ts, frontend/src/entities/region/model/mappers.ts, frontend/src/entities/region/model/types.ts, frontend/src/features/firmware_deploy/ui/RegionTable.tsx
- Region Entity와 관련된 타입과 API를 정의하였습니다. (추후 데이터베이스에 맞춰 업데이트 예정)
- Region Entity를 복수 선택할 수 있는 테이블 컴포넌트를 생성하였습니다.
N/A
N/A
=> [FrontEnd] Region Entity 구성 및 복수 선택 테이블 컴포넌트 생성

terraform/security_groups.tf
- RDS와 Lambda 전용 Security Groups를 생성하였습니다.
- Lambda는 RDS에 접근 가능하도록 설정하였습니다.
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "aws_security_group" "lambda_sg" {
+ arn                    = (known after apply)
+ description            = "Security group for Lambda functions"
+ egress                 = [
+ {
+ cidr_blocks      = [
+ "0.0.0.0/0",
]
+ description      = "Allow all outbound traffic"
+ from_port        = 0
+ ipv6_cidr_blocks = []
+ prefix_list_ids  = []
+ protocol         = "-1"
+ security_groups  = []
+ self             = false
+ to_port          = 0
},
]
+ id                     = (known after apply)
+ ingress …
```
=> [Terraform] RDS와 Lambda를 위한 Security Groups 생성

terraform/emqx.tf, terraform/security_groups.tf
- EC2 인스턴스에 EMQX를 세팅하였습니다.
- user_data를 통해 인스턴트가 실행될 때 EMQX를 설치하고 실행합니다.
- 원활한 개발을 위해 외부에서 MQTT 메시지를 보내고 구독할 수 있도록 Security Group을 구성하였습니다.
- MQTT 메시지 publish / subscribe 테스트
```
import paho.mqtt.client as mqtt
from paho.mqtt.enums import CallbackAPIVersion
broker_address = "3.38.104.113"
topic = "test/topic"
client = mqtt.Client(CallbackAPIVersion.VERSION2)
client.connect(broker_address, 1883, 60)
client.publish(topic, "Hello, MQTT!")  # 메시지 발행
print("Message published to topic:", topic)
client.disconnect()
import paho.mqtt.client as mqtt
from paho.mqtt.enums import CallbackAPIVersion
broker_address = "3.38.104.113"
topic = "test/topic"
def on_message(client, userdata, message):
print(f"Received message: {message.payload.decode()}")
client = mqtt.Client(CallbackAPIVersion.VERSION2) …
```
=> [Terraform] EMQX 세팅

backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/IotCloudOtaApplication.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/controller/FirmwareController.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/dto/ErrorResponseDto.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/dto/FirmwareMetadataRequestDto.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/dto/FirmwareMetadataResponseDto.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/dto/PresignedUrlRequestDto.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/dto/PresignedUrlResponseDto.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/entity/BaseEntity.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/entity/FirmwareMetadata.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/repository/FirmwareMetadataJpaRepository.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/service/FirmwareMetadataService.java, backend/iot-cloud-ota/src/main/resources/application.properties
- 펌웨어 메타데이터 저장 `POST` `API /api/firmwares/metadata` 추가
- Postman으로 메타데이터 저장 API 호출 테스트를 진행함
- 정상적으로 DB에 저장 확인
N/A
N/A
=> [Backend] 펌웨어 메타데이터 등록 API 구현

backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/component/MockDataInitializer.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/controller/FirmwareController.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/dto/FirmwareMetadataWithPageResponseDto.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/dto/PaginatedFirmwareMetadataResponseDto.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/dto/PaginationMetadataDto.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/exception/GlobalExceptionHandler.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/repository/FirmwareMetadataJpaRepository.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/service/FirmwareMetadataService.java
- `GET /api/firmwares/metadata` API 추가
- Native SQL 기반 쿼리(`LIMIT`, `OFFSET`) 으로 페이징 구현
- page/limit 유효성 검사 (page < 0, limit < 0시 400 에러 반환)
- Postman으로` /api/firmwares/meatadata` 요청 및 결과 확인
N/A
N/A
=> [Backend] 페이징 처리된 펌웨어 메타데이터 조회 기능 추가

backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/IotCloudOtaApplication.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/controller/FirmwareController.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/repository/FirmwareMetadataJpaRepository.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/service/FirmwareMetadataService.java
- `GET /api/firmwares/metadata/{id}` API 추가
- 존재하지 않는 ID 요청 시 `404 NOT_FOUND` 예외 처리
- 로컬에서 Postman을 이용해 테스트를 진행하였습니다.
- 존재하는 ID로 `/metadata/{id}` 요청
- 존재하지 않는 ID로 `/metadata/{id}` 요청
N/A
N/A
=> [Backend] 펌웨어 세부 정보 조회 API 구현

backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/controller/FirmwareController.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/dto/DownloadPresignedUrlResponseDto.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/service/S3Service.java
- GET /api/firmwares/{id}/presigned_download 엔트포인트 구현
- 지정된 펌웨어 ID에 대해 S3 Presigned 다운오르 URL을 생성하여 반환
- FirmwareMetadata 엔티티의 s3Path를 기반으로 Presigned URL 생성
- S3Service에 다운로드용 Presigned URL 생성 메서드 추가
- 로컬 환경에서 /api/firmwares/{id}/presigned_download API 호출 테스트
- 유효한 ID 요청 시 200 OK 및 유효한 Presigned URL 반환 확인
- 존재하지 않은 ID 요청 시 404 NOT_FOUND 반환 확인
N/A
N/A
=> [Backend] 펌웨어 파일 다운로드 요청  API 구현

backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/entity/Region.java, backend/iot-cloud-ota/src/main/resources/application.properties, backend/iot-cloud-ota/src/main/resources/data.sql
- region 엔티티 추가 (`id`, `region_id`, `region_name`)
- 초기 리전 데이터 삽입용 `data.sql` 구성
- `application.properties`에 `data.sql` 자동 실행 설정 추가
- 애플리케이션 실행 후 MySQL에서 `SELECT * FROM region;` 실행
- region 테이블 신규 생성됨
- 초기 데이터가 삽입되므로 운영 DB에 적용 시 주의 필요
- N/A
=> [Backend] Region 테이블 생성 및 초기 데이터 구성

backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/component/MockDataInitializer.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/controller/RegionController.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/domain/RegionSummary.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/dto/RegionSummaryResponseDto.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/repository/DivisionJpaRepository.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/repository/GroupJpaRepository.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/repository/RegionJpaRepository.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/service/DeviceService.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/service/RegionService.java, backend/iot-cloud-ota/src/main/resources/application.properties
- `GET /api/regions` 엔드포인트 추가
- 리전별 디바이스 등록 현황 을 조회하는 기능 구현
- `Region`, `Device` 테이블 조인 후 `RegionSummaryResponseDto`로 응답
- Postman을 이용해 `GET /api/regions` 호출
N/A
N/A
=> [Backend] 리전 summary 리스트 요청 API 구현

backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/controller/FirmwareController.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/repository/FirmwareMetadataJpaRepository.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/service/FirmwareMetadataService.java
- `/api/firmwares/metadata` API에 search 쿼리 파라미터 추가
- 펌웨어 버전(`version`) 및 릴리즈 노트(`release_note`)를 기준으로 LIKE 검색 가능하도록 기능 구현
- 전체 조회 및 검색 결과에 대해 페이지네이션 정보 함께 반환
- `GET /api/firmwares/metadata?search=연두` 요청 시 "연두"이 포함된 version 또는 release_note 레코드만 정상 반환되는지 확인
- `GET /api/firmwares/metadata` 요청 시 전체 데이터가 정상적으로 페이지네이션되어 반환되는지 확인
N/A
N/A
=> [Backend] 펌웨어 메타데이터 검색 기능 추가

backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/controller/DeviceController.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/controller/DivisionController.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/controller/FirmwareController.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/controller/S3Controller.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/entity/FirmwareMetadata.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/repository/FirmwareMetadataJpaRepository.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/service/FirmwareMetadataService.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/service/S3Service.java
- 업로드 Presigned URL 요청 API의 HTTP 메서드를 `GET`에서 `POST`로 변경
- 변경 전: `GET /api/firmwares/presigned_upload`
- 변경 후: `POST /api/s3/presigned_upload` (Body에 version, fileName 포함)
- 다운로드 Presigned URL 요청 시 `firmwareId` 기반 조회에서 `version`과 `fileName` 기반 조회로 파라미터 변경
- 변경 전: `GET /api/firmwares/presigned_download`
- 변경 후: `GET /api/s3/presigned_download?version=v1.0.0&fileName=firmware.bin`
- Postman을 통해 요청 및 응답 확인
- 프론트엔드 측 API 요청 방식 변경 필요
- 업로드는 `POST` 요청 전송으로 수정해야 함
- 다운로드는 `firmwareId` 대신 version + fileName으로 요청하도록 수정 필요
- 기존 `firmwareId` 기반 다운로드 API와는 호환되지 않음
- 클라이언트 측 수정 이후 정상 동작 가능
=> [Backend] 펌웨어 Presigned URL 관련 API 수정

frontend/src/entities/firmware/ui/FirmwareDetail.tsx, frontend/src/features/firmware_register/api/api.ts, frontend/src/features/firmware_register/model/types.ts, frontend/src/features/firmware_register/ui/FirmwareRegister.tsx, frontend/src/pages/FirmwarePage.tsx, terraform/buckets.tf
- 펌웨어 등록 기능을 정의하는 `features/firmware_register` 디렉토리를 생성하였습니ㅏㄷ.
- 폼 데이터를 입력받은 후 서버에 펌웨어 파일과 메타데이터를 업로드하는 로직을 구현하였습니다.
1. 서버에 Presigned URL 발급을 요청합니다.
2. 발급받은 Presigned URL을 통해 펌웨어 파일을 업로드합니다.
3. 펌웨어의 메타데이터 등록 요청을 서버에 보냅니다.
- 아직 프론트의 도메인이 고정되지 않았으므로 원활한 개발을 위해 S3 버킷의 CORS를 Public하게 설정하였습니다.
`junwoo-25.7.16`이라는 버전으로 `2.out`이라는 파일 테스트 업로드
- 펌웨어 메타데이터 정보 확인
- S3 버킷에 업로드 확인
N/A
N/A
=> [FrontEnd] [Terraform] Firmware 등록 API 연결

backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/component/MockDataInitializer.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/entity/FirmwareMetadata.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/exception/GlobalExceptionHandler.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/service/FirmwareMetadataService.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/service/S3Service.java
- S3 버킷에 저장된 파일의 내용을 스트리밍 방식으로 읽고, 해당 파일의 SHA-256 해시 값을 계산하는 `calculateS3FileHash` 메서드 구현
- 바이트 배열을 16진수 문자열로 변환하는 `bytesToHex` 메서드 구현
- 펌웨어 메타데이터 등록 시, 전달받은 S3 경로의 파일을 읽어 해시 값을 계산한 후 해당 해시를 DB에 함께 저장하도록 로직 추가
- S3에 업로드된 파일에 대해 `calculateS3FileHash` 실행하여 SHA-256 해시 값을 정상적으로 반환하는지 확인함
- 테스트 파일 해시를 로컬에서 동일하게 계산한 결과와 비교하여 일치함을 확인함
N/A
N/A
=> [Backend] S3 파일의 SHA-256 해시 계산 메서드 추가

terraform.tfstate, terraform/vpc.tf
- ECS 서비스를 디버깅, 관리하기 위해 원격 접속을 가능하게 하는 SSM 서비스를 활성화하였습니다.
- VPC Endpoint를 추가하여 Private Subnet에 있는 서비스도 접속 가능하도록 하였습니다.
- 원격 접속 테스트
```bash
aws ecs execute-command \
--region ap-northeast-2 \
--cluster iot-cloud-ota-cluster \
--task {내 테스크}
--container emqx \
--command "/bin/bash" \
--interactive
```
N/A
N/A
=> [Cloud/Infra] ECS 서비스 원격 접속을 위한 세션 매니저 구성

backend/iot-cloud-ota/Dockerfile
- 기존에 수동으로 Gradle build하던 것을 Dockerfile에서 빌드를 포함해서 수행하도록 변경하였습니다.
N/A
N/A
=> [Cloud/Infra] 백엔드 서버 Dockerfile에 Gradle Build 추가

terraform/emqx.tf
- MQTT 핸들러와 기기의 MQTT 클라이언트가 현재 개발 진행중이고 인증서를 갱신하는 로직이 개발 진행중인 관계로, 1883 포트를 활성화하여 MQTT without TLS를 가능하게 합니다.
- MQTT Subscribe 테스트
```
import paho.mqtt.client as mqtt
def on_connect(client, userdata, flags, rc):
if rc == 0:
print("Connected to EMQX with mTLS!")
client.subscribe("test/topic")
else:
print("Failed to connect, return code %d\n", rc)
def on_message(client, userdata, msg):
print(f"Received message '{msg.payload.decode()}' on topic '{msg.topic}'")
client = mqtt.Client()
client.on_connect = on_connect
client.on_message = on_message
broker_address = <우리 브로커 주소>
port = 1883
client.connect(broker_address, port)
client.loop_forever()
```
N/A
N/A
=> [Cloud/Infra] 개발을 위해 EMQX 1883 포트 임시 활성화

terraform/ecs.tf, terraform/security_groups.tf, terraform/vpc.tf
- 현재 모든 서비스는 Private Subnet에 배치되어 있고, AWS의 퍼블릭 서비스(S3, CloudWatch 등)에 접근하기 위해서 `VPC Endpoint`를 사용해왔습니다. 하지만 CloudFront에 접근하여 Signed URL을 발급받아야 하는데 **CloudFront는 VPC Endpoint를 지원하지 않는 문제**가 발생하였습니다.
- 따라서 VPC Endpoint로 접근하는 방법 대신 **NAT 게이트웨이를 설정하여 Private Subnet이 인터넷으로 접근 가능하도록 변경**하였습니다.
- Private Subnet의 Spring Boot가 CloudFront에 정상적으로 접근할 수 있는지 검증
N/A
N/A
=> [Cloud/Infra] Private Subnet이 AWS Public Service에 접근하기 위한 NAT 구성

frontend/src/pages/MonitoringPage.tsx
- 프론트엔드의 Grafana 대시보드에 `from`, `to` 가 설정되어 있어 업데이트되지 않는 현상을 해결하였습니다.
N/A
N/A
=> [Cloud/Infra] Grafana 대시보드 Real-Time 수정

terraform/quest_db.tf, terraform/security_groups.tf
- `AWS TimeStream`이 신규 생성이 불가능해지게 되었고, `AWS Timestream for InfluxDB`는 최소 월 10만원 이상의 비용이 나올 것으로 예상됩니다. 따라서 **오픈소스 시계열 데이터베이스를 EC2에 구성**할 필요가 생겼습니다.
- 경량이고, 속도가 매우 빠른 것이 검증된 `QuestDB`를 EC2인스턴스에 구성하였습니다.
- Private Subnet에 배치하고, Bastion 서버가 SSH 연결로 접속 가능하도록 하여 로컬에서 SSH 터널링이 가능하도록 구성하였습니다. (개발의 편의를 위해서)
- `EBS` 를 연결하여 인스턴스가 재시작되더라도 데이터를 유지할 수 있도록 구성하였습니다.
- SSH 터널링 이후 9000번 포트에 접속한 결과 화면
- Python 라이브러리를 사용해 정상적으로 데이터가 쓰여지는지 확인
```
from questdb.ingress import Sender, TimestampNanos
import numpy as np
conf = f'http::addr=localhost:19000;'
with Sender.from_conf(conf) as sender:
sender.row(
'trades',
symbols={
'symbol': 'ETH-USD',
'side': 'sell'
},
columns={
'price': 2615.54,
'amount': 0.00044,
'ord_book_bids': np.array([2615.54, 2618.63]),
},
at=TimestampNanos.now())
sender.flush()
```
N/A
N/A
=> [Cloud/Infra] 시계열 데이터베이스 QuestDB 구성

terraform/nat_instance.tf, terraform/security_groups.tf, terraform/vpc.tf
- 현재 NAT Gateway로 인해 너무 많은 비용이 발생하고 있습니다. 트래픽은 없지만, 켜놓는 것만으로도 한 달에 $150 달러 정도의 비용이 발생할 것으로 예상됩니다.
- 개발하는 동안 **비용을 줄이기 위해 NAT Gateway를 주석 처리**하고, **NAT Instance를 구성**하였습니다.
- NAT Instance의 인스턴스 타입은 `t3.nano`로 설정하였습니다.
- NAT Instance가 NAT로 동작하기 위해 `source_dest_check = false`로 설정하고, `user_data`에 NAT 관련 설정을 추가하였습니다. ([이 링크 참고](https://docs.aws.amazon.com/ko_kr/vpc/latest/userguide/work-with-nat-instances.html#create-nat-ami))
- Backend 서비스를 재배포하여 ECR, Cloud Watch 등에 정상적으로 접근하는지 확인
- Backend에서 CloudFront의 Signed URL을 정상적으로 발급할 수 있는지 확인
N/A
N/A
=> [Terraform] NAT Gateway를 NAT Instance로 대체

frontend/src/features/firmware_deploy/api/api.ts, frontend/src/features/firmware_deploy/ui/FirmwareDeploy.tsx
- 펌웨어 배포 요청을 클릭하면 실행되는 `handleDeploy()` 함수를 작성하였습니다.
- 먼저 리전, 그룹, 디바이스 중 하나도 선택되지 않으면 유효하지 않은 요청으로 간주합니다.
- `requestFirmwareDeploy()` 함수를 호출합니다.
- `requestFirmwareDeploy()`함수는 펌웨어 배포를 요청하는 API를 호출합니다.
- 프론트에서 `bartooler-002(id:2)`, `bartooler-003(id:3)`에 대해 배포 요청
https://github.com/user-attachments/assets/7eb301ab-9f2a-4c48-9111-a6ac0344eca2
- 서버 로그 출력
N/A
N/A
=> [Frontend] 펌웨어 배포 API 요청 함수 구현

frontend/src/entities/firmware_deployment/ui/FirmwareDeploymentList.tsx
- 배포 진행상황 바 너비를 w-3/4 로 고정하여 기기 개수에 상관없이 동일한 너비를 갖도록 수정하였습니다.
- 변경전
- 변경후
N/A
N/A
=> [Frontend] 배포 진행상황 가로 폭 고정

frontend/src/app/Router.tsx, frontend/src/entities/firmware_deployment/api/useFirmwareDeploymentDetail.tsx, frontend/src/entities/firmware_deployment/model/types.ts, frontend/src/entities/firmware_deployment/ui/DeploymentDeviceStatusBadge.tsx, frontend/src/entities/firmware_deployment/ui/DeploymentProgressBar.tsx, frontend/src/entities/firmware_deployment/ui/DeploymentStatusBadge.tsx, frontend/src/entities/firmware_deployment/ui/FirmwareDeploymentList.tsx, frontend/src/pages/FirmwareDeploymentDetailPage.tsx
- 펌웨어 배포 데이터를 나타내기 위한 컴포넌트들을 작성하였습니다.
- `DeploymentProgressBar`: 배포 진행 상태를 바 형태로 시각화하는 컴포넌트
- `DeploymentStatusBadge`: 배포 진행 상태를 뱃지 형태로 나타내는 컴포넌트
- `DeploymentDeviceStatusBadge`: 배포 내 각 기기별 상태를 뱃지 형태로 나타내는 컴포넌트
- 펌웨어 배포들을 **카드 리스트**로 나타내는 `FirmwareDeploymentList`를 구현하였습니다.
- 펌웨어 세부 정보 API 를 요청하여 데이터를 가져오는 커스텀 훅 `useFirmwareDeploymentDetail`을 작성하였습니다.
- Mock 데이터로 테스트
https://github.com/user-attachments/assets/a374a422-6e5b-4a58-873e-884f7741113f
N/A
N/A
=> [Frontend] 배포 세부 정보 페이지 구현

frontend/src/entities/firmware_deployment/api/api.ts, frontend/src/entities/firmware_deployment/model/mappers.ts, frontend/src/entities/firmware_deployment/model/types.ts, frontend/src/entities/firmware_deployment/ui/DeploymentDeviceStatusBadge.tsx, frontend/src/entities/firmware_deployment/ui/FirmwareDeploymentList.tsx, frontend/src/features/firmware_deploy/api/api.ts, frontend/src/features/firmware_deploy/model/types.ts, frontend/src/features/firmware_deploy/ui/FirmwareDeploy.tsx, frontend/src/pages/FirmwareDeploymentDetailPage.tsx
백엔드 API 응답 구조가 변경됨에 따라 프론트엔드의 DTO, 모델을 그에 맞게 변경하였습니다.
- API URL
- `/api/firmware-deployments` -> `/api/firmwares/deployment/list` 변경
- `/api/firmware-deployments/${id}` -> `/api/firmwares/deployment/{id}` 변경
- 디바이스 다운로드 상태 (FirmwareDeploymentDeviceStatus)
- `WAITING` 추가
- 배포 리스트
- `deploymentType` 추가
- `target` -> `targetInfo` 변경
- `totalDevices` -> `totalCount` 변경
- `startedAt` -> `deployedAt` 변경
- `expiredAt` -> `expiresAt` 변경
- 기타 등등
- 렌더링 확인
N/A
N/A
=> [Frontend] 백엔드 API 응답 변경에 따른 DTO, 모델 변경

frontend/src/features/firmware_deploy/api/api.ts, terraform/buckets.tf
기존에 S3 페이지를 새로고침하면 404 Not Found - No Such Key 에러가 뜨는 현상이 발생하였습니다.
이는 React가 SPA이고 `index.html`을 받아서 `react-router-dom`으로 주소창 URL만 바꾸고 다른 컴포넌트를 로딩하는 형식이기 때문에, 새로고침 시 `index.html`이 아닌 실제 해당 URL에 있는 리소스를 다운로드받으려고 해서 발생하는 현상입니다.
- S3 파일이 존재하지 않아서 404 오류가 발생하는 경우, `index.html`을 반환하도록 설정하였습니다. (이렇게 하면 사용자는 index.html을 받아서 정상적으로 react-router-dom이 실행되고 해당 URL의 컴포넌트를 렌더링합니다.
- DocString에 Typo를 발견하여 수정하였습니다.
https://github.com/user-attachments/assets/521d490c-8732-4952-8913-9947af3d5e07
N/A
N/A
=> [Frontend] S3 호스팅 웹페이지 새로고침 시 NotFound 에러 해결

backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/repository/QuestDbRepository.java, mqtt-handler/init/cmd/cmd.go, mqtt-handler/mqttclient/client.go
- MQTT 클라이언트에 연결 안정성 옵션 추가
- OnConnect 콜백에서 SubscribeAllTopics() 실행하여 재연결 시 자동 구독 복구
- 로컬 환경에서 EMQX 브로커와 연결 후 네트워크를 강제로 끊고 다시 연결
- 재연결 성공 확인 후 `SubscribeAllTopics()`가 실행되어 정상적으로 토픽 구독이 복구됨 확인
N/A
N/A
=> [Mqtt handler] 자동 재연결 및 재구독 로직 추가

backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/entity/FirmwareDeployment.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/enums/DeploymentType.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/repository/DivisionJpaRepository.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/repository/RegionJpaRepository.java
- device 없는 division/region도 count 0으로 조회되도록 수정하였습니다
- region 조회 
- division 조회
N/A
N/A
=> [Backend] Division/Region 집계 쿼리 수정

frontend/src/features/firmware_deploy/api/api.ts, frontend/src/features/firmware_deploy/api/useFirmwareDeploy.tsx, frontend/src/features/firmware_deploy/ui/FirmwareDeploy.tsx
- 배포 요청을 토스트 메시지로 변경하였습니다.
- PENDING, SUCCESS, ERROR 에 대해 토스트 메시지로 알려주도록 구성했습니다.
- 배포 요청 시 현재 배포 리스트 `firmware-deployments` 키에 대한 캐시 값을 무효화합니다. 이는 배포 리스트에 새로운 배포를 포함하기 위함입니다.
https://github.com/user-attachments/assets/27e20f2d-4f99-4467-bf03-761b961bb1fb
N/A
N/A
=> [Frontend] 배포 요청 토스트 메시지로 변경

frontend/src/app/Router.tsx, frontend/src/entities/advertisement/api/api.ts, frontend/src/entities/advertisement/api/useAdDetail.tsx, frontend/src/entities/advertisement/model/types.ts, frontend/src/entities/advertisement/ui/AdDetail.tsx, frontend/src/entities/device/model/types.ts, frontend/src/entities/device/ui/DeviceList.tsx, frontend/src/pages/AdDetailPage.tsx, mqtt-handler/config/config.go
- `/ads/:id` PATH를 광고 세부 페이지 컴포넌트와 연결하였습니다.
- 광고 세부정보 데이터를 가져오는 `getAdDetail()` 함수를 Advertisement Entity API Service에 추가하였습니다.
- 광고 세부 정보를 가져오는 커스텀 훅 `useAdDetail`을 생성하였습니다.
- `광고 세부 정보 + 현재 광고를 표시중인 기기 목록`을 광고 세부 정보 페이지로 생성하였습니다.
N/A
N/A
=> [Frontend] 광고 세부 정보 페이지 구현

frontend/src/entities/advertisement/ui/AdList.tsx, frontend/src/features/ad_deploy/api/api.ts, frontend/src/features/ad_deploy/api/useAdDeploy.tsx, frontend/src/features/ad_deploy/model/types.ts, frontend/src/features/ad_deploy/ui/AdDeploy.tsx, frontend/src/features/ad_deploy/ui/DeviceTable.tsx, frontend/src/features/ad_deploy/ui/GroupTable.tsx, frontend/src/features/ad_deploy/ui/RegionTable.tsx, frontend/src/pages/AdListPage.tsx
- `AdListPage` 컴포넌트에 `배포하기` 버튼을 클릭하면 최대 3개의 광고를 체크 표시하여 배포 타깃으로 설정할 수 있도록 구성하였습니다.
- 배포 모달창에 배포 타겟인 광고들의 미리보기를 표시하고, 배포 타겟을 선택할 수 있도록 하였습니다.
- `useAdDeploy` 뮤테이션 + `toast.promise`를 사용하여 배포 요청을 실행하도록 하였습니다.
https://github.com/user-attachments/assets/b1039f59-8e8b-4799-85df-a034ddc99909
N/A
N/A
=> [Frontend] 광고 배포 모달창 구현

grafana/dashboards/firmware_download_progress.json
- 펌웨어 다운로드 진행상태 대시보드를 구현하였습니다.
- `command-id`와 `device-id`을 variables로 받아, 임베딩 시 원하는 배포의 원하는 기기를 가져올 수 있도로 구성하였습니다.
N/A
N/A
=> [Grafana] 펌웨어 다운로드 진행 상태 바 구현

backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/entity/DeviceAds.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/entity/DeviceFirmware.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/entity/FirmwareDownloadEvents.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/repository/AdsMetadataJpaRepository.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/repository/DeviceAdsJpaRepository.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/repository/QuestDbRepository.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/service/DeployJudgeScheduler.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/service/DeviceService.java
- 기기별 광고 히스토리를 저장하는 `device_ads` 테이블 추가
- 기기별 펌웨어 히스토리를 저장하는 `device_firmware` 테이블 추가
- 광고 배포 완료 시 `device_ads` 테이블에 광고 이력 업데이트/삽입 로직 추가
- 펌웨어 배포 완료 시 `device_firmware` 테이블에 광고 이력 업데이트/삽입 로직 추가
- 기존 활성 광고/펌웨어 (ended_at IS NULL) → `ended_at` 현재 시간으로 업데이트
- 새로운 광고/펌웨어 → started_at = now() 로 삽입
- 로컬 환경에서 광고/펌웨어 배포 완료 후 테이블 업데이트 확인
- 기기별 광고 히스토리를 저장하는 `device_ads` 테이블
- 기기별 펌웨어 히스토리를 저장하는 `device_firmware` 테이블
N/A
N/A
=> [Backend] 광고/펌웨어 배포 완료 시 광고/펌웨어 히스토리 저장 로직 추가

mqtt-handler/mqttclient/client.go, mqtt-handler/mqttclient/sales_subscriber.go, mqtt-handler/repository/event_consumer.go, mqtt-handler/repository/questdb_repository.go, mqtt-handler/types/sales.go
- MQTT 토픽 `v1/{기기ID}/sales/data` 구독 로직 추가
- QuestDB `sales_data` 테이블 생성 및 저장 로직 구현
- 로컬 환경에서 기기 → 클라우드로 sales 이벤트 publish 후 DB 저장 확인
- `type`, `sub_type`, `timestamp` 필드 정상 반영 확인
N/A
N/A
=> [Mqtt Handler] 매출/거래 데이터 관련 Mqtt Topic 구독 및 QuestDB sales_data 테이블 추가

frontend/src/entities/group/api/api.ts
- 배포 모달 창에서 그룹 리스트를 조회할 때 사용되는 API가 변경되었습니다. `/api/divisions` -> `/api/groups`. 이에 따라 API 호출 URL을 동기화하였습니다.
N/A
N/A
=> [Frontend] 변경된 그룹 API와 동기화

frontend/src/app/Router.tsx, frontend/src/entities/device/api/api.ts, frontend/src/entities/device/api/useDeviceDetail.tsx, frontend/src/entities/device/model/types.ts, frontend/src/entities/device/ui/DeviceCard.tsx, frontend/src/entities/device/ui/DeviceDetailView.tsx, frontend/src/pages/DeviceDetailPage.tsx
- 기기 상세 정보를 보여주는 페이지를 구현하였습니다.
- 두 개의 MainTile로 나누고, 첫번째에는 기기 관련 정보와 메트릭 그래프 표시, 두번째에는 표시중인 광고를 보여주도록 구성하였습니다.
- 기기 상세 정보 API를 요청하는 `getDeviceDetail()` 을 구현하였습니다.
N/A
N/A
=> [Frontend] 기기 상세 정보 페이지 구현

backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/dto/DeviceDetailResponseDto.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/dto/DeviceSummaryResponseDto.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/service/DeviceService.java
- `/api/devices/{id}`, `/api/devices` 응답 DTO에 isActive 필드 추가
- 최근 5분 이내 상태 여부를 기준으로 활성화 여부 반환
- 로컬에서 API 호출 시 `isActive` 값 정상 반환 확인
- `/api/devices`
- `/api/devices/{id}
N/A
N/A
=> [Backend] 기기 활성화 상태를 최근 5분 이내 여부로 판별하도록 로직 추가

mqtt-handler/mqttclient/status_subscriber.go, mqtt-handler/repository/event_consumer.go, mqtt-handler/types/status.go
- `firmware_status`의 컬럼 `firmware_id(Int64)` 제거, `firmware_version(String)`으로 변경
- QuestDB 테이블 스키마 수정 반영
- 로컬 환경에서 이벤트 insert 시 `firmware_version` 정상 저장 확인
- DB 스키마 변경 사항 있음 (기존 `firmware_id` 컬럼 제거, `firmware_version` 추가)
N/A
=> [Mqtt Handler] QuestDB 테이블 스키마 수정 반영

frontend/src/entities/firmware/api/api.ts, frontend/src/entities/group/api/api.ts, frontend/src/entities/region/api/regionApi.ts, frontend/src/features/device_filter/ui/DeviceFilter.tsx
- `DeviceFilter`에 그룹 / 리전을 생성하는 기능을 추가하였습니다.
- 드롭다운 최하단에, `+ 추가하기` 버튼을 누르면 생성 가능하도록 하였습니다.
- 그룹 추가: `POST /api/groups`
- 리전 추가: `POST /api/regions`
- 백엔드에서 펌웨어 다운로드 요청 엔드포인트가 `/api/s3/firmware/presigned_download` 에서 `/api/s3/firmware/download` 로 변경되어 동기화하였습니다.
N/A
N/A
=> [Frontend] 그룹 / 리전 생성 기능 구현

backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/config/RestClientConfig.java
- RestClientConfig에서 Connection Timeout과 Read Timeout을 기존 5초 → 60초로 수정
- 외부 서비스 응답 지연 시 불필요한 TimeoutException 발생을 방지하기 위함
- 로컬 환경에서 MQTT Handler 연동 시 5초 이상 지연되는 요청 테스트
- Timeout 예외 발생하지 않고 정상 응답 수신 확인
- 단위 테스트/통합 테스트에서 RestClient 호출 정상 동작 검증
- N/A (서버 재시작 시 자동 반영됨)
- DB 마이그레이션 없음
- Timeout 값 증가로 인해 외부 서비스 지연 시 대기 시간이 최대 60초까지 늘어날 수 있음
- 기존 버전과 호환성 문제 없음
- 클라이언트/서버 간 동기화 영향 없음
=> [Backend] RestClient connection/read timeout 수정

mqtt-handler/init/cmd/cmd.go, mqtt-handler/mqttclient/publisher.go, mqtt-handler/network/advertisement.go, mqtt-handler/network/firmware.go, mqtt-handler/network/root.go
- 펌웨어, 광고를 배포 시 `Wait Group`으로 동시에 Publish하지 않고, 시간 간격(10ms)를 두어 Publish 하도록 변경하였습니다.
- 펌웨어, 광고 배포 메시지 QoS를 2에서 1로 변경하였습니다.
- `network`의 `newFirmwareRouter`, `newAdsRouter`에서 `mqtt.NewMqttClient()`를 사용하면 싱글톤을 위반하여 중복된 Client ID가 생성될 수 있으므로 `root.go`에서 생성된 싱글톤 MQTT Client를 주입하는 방법으로 변경하였습니다.
- 1000개의 메시지 Publish 이후 `Connect Lost: EOF` 오류 발생 여부 확인
N/A
N/A
=> [Mqtt Handler] 대량 배포 시 MQTT 연결이 끊어지는 현상 해결

mqtt-handler/init/cmd/cmd.go, mqtt-handler/mqttclient/client.go, mqtt-handler/mqttclient/publisher.go, mqtt-handler/repository/event_consumer.go, mqtt-handler/repository/questdb_repository.go
- LineSender 고루틴 동시 사용으로 인한 데이터 섞임/파싱 에러 수정
- Consumer별 독립 DBClient 생성하여 안전하게 QuestDB에 저장하도록 변경
- MQTT 메시지 수신 후 QuestDB 테이블별 데이터 정상 적재 확인
- system_status, download_events 등 테이블 데이터가 섞이지 않음 확인
N/A
N/A
=> [Mqtt Handler] 고루틴 동시 사용 문제 해결을 위해 Consumer별 DBClient 분리

backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/controller/DeviceController.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/dto/AdsDeploymentDto.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/dto/DeviceRegisterRequestDto.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/dto/DeviceRegisterResponseDto.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/dto/GenerateRegistrationCodeRequestDto.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/dto/GenerateRegistrationCodeResponseDto.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/entity/Device.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/service/DeploymentService.java, backend/iot-cloud-ota/src/main/java/com/coffee_is_essential/iot_cloud_ota/service/DeviceService.java, mqtt-handler/config/config.go, mqtt-handler/mqttclient/client.go, mqtt-handler/mqttclient/device_subscriber.go, mqtt-handler/mqttclient/publisher.go, mqtt-handler/types/advertisement.go, mqtt-handler/types/device.go
- `POST /api/devices` 기기 등록 코드 발급 API 추가
- 광고 배포 시 MQTT 메시지에 `total_size` 필드 포함
- 기기 등록용 MQTT 토픽(`v1/{deviceId}/regist`) 구독 및 Spring 연동
- 등록 결과를 `v1/{deviceId}/regist/ack` 토픽으로 publish
- 기기 등록 코드 발급 API 호출 시 정상적으로 코드와 만료 시간 반환 확인
- 광고 배포 메시지에 total_size 값 포함 여부 확인
- MQTT 구독/발행 흐름 (regist → Spring 검증 → regist/ack) 정상 동작 검증
- 기기 등록 후 DB 저장 확인
N/A
N/A
=> [Backend/Mqtt Handler] 기기 등록 코드 발급 API 및 MQTT regist/ack 토픽 추가
